name: autism_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.6
  supabase_flutter: ^2.8.3
  flutter_tts: ^4.2.1
  audioplayers: ^6.1.0
  fl_chart: ^0.70.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # الصور
    - assets/images/Blue and Green.png
    - assets/images/apple.jpg
    - assets/images/Blue.png
    - assets/images/Ellipse 25.png
    - assets/images/story BG.png
    - assets/images/game BG.png

    # الصور للقصص
    - assets/images/forest.png
    - assets/images/friends.png
    - assets/images/kingdom.png

    # sentence_game
    - assets/images/sentence_game/

  # الاصوات
  # Add your audio assets here (if any)
